-- MySQL Script generated by MySQL Workbench
-- Fri Jun  9 21:26:28 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema clarotexsas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `clarotexsas` ;

-- -----------------------------------------------------
-- Schema clarotexsas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clarotexsas` DEFAULT CHARACTER SET utf8 ;
USE `clarotexsas` ;

-- -----------------------------------------------------
-- Table `clarotexsas`.`tipoInventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clarotexsas`.`tipoInventario` (
  `idtipoInventario` CHAR(1) NOT NULL,
  `descripcion` VARCHAR(15) NULL,
  PRIMARY KEY (`idtipoInventario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clarotexsas`.`telas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clarotexsas`.`telas` (
  `idtelas` INT NOT NULL AUTO_INCREMENT,
  `referencia` VARCHAR(7) NULL,
  `descripcion` TEXT(255) NULL,
  `costo` DOUBLE NULL,
  PRIMARY KEY (`idtelas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clarotexsas`.`unidaddeMedidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clarotexsas`.`unidaddeMedidas` (
  `idunidaddeMedidas` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(10) NULL,
  PRIMARY KEY (`idunidaddeMedidas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clarotexsas`.`inventarioTelas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clarotexsas`.`inventarioTelas` (
  `idinventarioTelas` INT NOT NULL AUTO_INCREMENT,
  `cantidad` DOUBLE NULL,
  `disponible` DOUBLE NULL,
  PRIMARY KEY (`idinventarioTelas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clarotexsas`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clarotexsas`.`estados` (
  `idestados` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idestados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clarotexsas`.`detallesTelas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clarotexsas`.`detallesTelas` (
  `iddetallesTelas` INT NOT NULL AUTO_INCREMENT,
  `idTipo` CHAR(1) NOT NULL,
  `idTela` INT NOT NULL,
  `idUniMedida` INT NOT NULL,
  `idInventario` INT NOT NULL,
  `idEstado` INT NOT NULL,
  `rendimiento` DOUBLE NULL,
  `color` VARCHAR(15) NULL,
  `ancho` DOUBLE NULL,
  PRIMARY KEY (`iddetallesTelas`),
  CONSTRAINT `idTela`
    FOREIGN KEY (`idTela`)
    REFERENCES `clarotexsas`.`telas` (`idtelas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idTipo`
    FOREIGN KEY (`idTipo`)
    REFERENCES `clarotexsas`.`tipoInventario` (`idtipoInventario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idUniMedida`
    FOREIGN KEY (`idUniMedida`)
    REFERENCES `clarotexsas`.`unidaddeMedidas` (`idunidaddeMedidas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idInventario`
    FOREIGN KEY (`idInventario`)
    REFERENCES `clarotexsas`.`inventarioTelas` (`idinventarioTelas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idEstado`
    FOREIGN KEY (`idEstado`)
    REFERENCES `clarotexsas`.`estados` (`idestados`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `idTela_idx` ON `clarotexsas`.`detallesTelas` (`idTela` ASC);

CREATE INDEX `idTipo_idx` ON `clarotexsas`.`detallesTelas` (`idTipo` ASC);

CREATE INDEX `idUniMedida_idx` ON `clarotexsas`.`detallesTelas` (`idUniMedida` ASC);

CREATE INDEX `idInventario_idx` ON `clarotexsas`.`detallesTelas` (`idInventario` ASC);

CREATE INDEX `idEstado_idx` ON `clarotexsas`.`detallesTelas` (`idEstado` ASC);


-- -----------------------------------------------------
-- Table `clarotexsas`.`insumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clarotexsas`.`insumos` (
  `idinsumos` INT NOT NULL AUTO_INCREMENT,
  `referencia` VARCHAR(7) NULL,
  `descripcion` TEXT(255) NULL,
  `costo` DOUBLE NULL,
  PRIMARY KEY (`idinsumos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clarotexsas`.`inventarioInsumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clarotexsas`.`inventarioInsumos` (
  `idinventarioInsumos` INT NOT NULL AUTO_INCREMENT,
  `cantidad` DOUBLE NULL,
  `disponible` DOUBLE NULL,
  PRIMARY KEY (`idinventarioInsumos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clarotexsas`.`detallesInsumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clarotexsas`.`detallesInsumos` (
  `iddetallesInsumos` INT NOT NULL AUTO_INCREMENT,
  `idTipo` CHAR(1) NOT NULL,
  `idInsumo` INT NOT NULL,
  `idUniMedida` INT NOT NULL,
  `idInventario` INT NOT NULL,
  `idEstado` INT NOT NULL,
  `color` VARCHAR(15) NULL,
  `talla` VARCHAR(10) NULL,
  PRIMARY KEY (`iddetallesInsumos`),
  CONSTRAINT `idTipoI`
    FOREIGN KEY (`idTipo`)
    REFERENCES `clarotexsas`.`tipoInventario` (`idtipoInventario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idInsumoI`
    FOREIGN KEY (`idInsumo`)
    REFERENCES `clarotexsas`.`insumos` (`idinsumos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idUniMedidaI`
    FOREIGN KEY (`idUniMedida`)
    REFERENCES `clarotexsas`.`unidaddeMedidas` (`idunidaddeMedidas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idInventarioI`
    FOREIGN KEY (`idInventario`)
    REFERENCES `clarotexsas`.`inventarioInsumos` (`idinventarioInsumos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idEstadoI`
    FOREIGN KEY (`idEstado`)
    REFERENCES `clarotexsas`.`estados` (`idestados`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `idTipoI_idx` ON `clarotexsas`.`detallesInsumos` (`idTipo` ASC);

CREATE INDEX `idInsumoI_idx` ON `clarotexsas`.`detallesInsumos` (`idInsumo` ASC);

CREATE INDEX `idUniMedidaI_idx` ON `clarotexsas`.`detallesInsumos` (`idUniMedida` ASC);

CREATE INDEX `idInventarioI_idx` ON `clarotexsas`.`detallesInsumos` (`idInventario` ASC);

CREATE INDEX `idEstadoI_idx1` ON `clarotexsas`.`detallesInsumos` (`idEstado` ASC);


-- -----------------------------------------------------
-- Table `clarotexsas`.`perfiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clarotexsas`.`perfiles` (
  `idperfil` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clarotexsas`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clarotexsas`.`usuarios` (
  `cedula` VARCHAR(13) NOT NULL,
  `nombre` VARCHAR(90) NULL,
  `email` VARCHAR(90) NULL,
  `usuario` VARCHAR(15) NULL,
  `password` VARCHAR(15) NULL,
  `perfil` INT NOT NULL,
  PRIMARY KEY (`cedula`),
  CONSTRAINT `idPerfil`
    FOREIGN KEY (`perfil`)
    REFERENCES `clarotexsas`.`perfiles` (`idperfil`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `idPerfil_idx` ON `clarotexsas`.`usuarios` (`perfil` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
